# Generated by Django 4.0.5 on 2022-06-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='clothing',
            options={'ordering': ('name',), 'verbose_name_plural': 'Одежда'},
        ),
        migrations.AlterIndexTogether(
            name='clothing',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='clothing',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothing', to='clothing_store.category'),
        ),
        migrations.RemoveField(
            model_name='clothing',
            name='slug',
        ),
    ]
