# Generated by Django 4.0.5 on 2022-06-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0002_alter_item_options_remove_clothing_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothing',
            old_name='category',
            new_name='brand',
        ),
    ]
