# Generated by Django 4.0.5 on 2022-06-12 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0003_clothing_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='image',
        ),
    ]
