# Generated by Django 4.0.5 on 2022-06-20 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0003_rename_category_clothing_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clothing_store.brand'),
            preserve_default=False,
        ),
    ]
