# Generated by Django 4.0.5 on 2022-06-20 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0004_item_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothing',
            name='brand',
        ),
    ]
