# Generated by Django 4.0.5 on 2022-06-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0005_remove_clothing_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
