# Generated by Django 4.0.4 on 2022-06-03 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='id',
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.brand'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='car_body',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.FloatField(),
        ),
    ]
