# Generated by Django 4.0.4 on 2022-06-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_remove_brand_id_alter_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
