# Generated by Django 4.0.4 on 2022-06-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_carmodel_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.FloatField(blank=True),
        ),
    ]
