# Generated by Django 4.0.4 on 2022-06-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_engine_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engine',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
