# Generated by Django 4.0 on 2022-06-20 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0005_remove_clothing_available_remove_clothing_created_and_more'),
        ('orders', '0003_rename_clothes_order_clothing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='clothing',
            field=models.ManyToManyField(related_name='orders', to='clothing_store.Clothing'),
        ),
    ]
