# Generated by Django 4.0.5 on 2022-06-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
        ('orders', '0004_rename_item_order_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='carts',
            field=models.ManyToManyField(related_name='orders', to='carts.cart'),
        ),
    ]
