# Generated by Django 4.0.5 on 2022-06-21 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0006_alter_brand_name_alter_clothing_name'),
        ('orders', '0005_remove_order_items_order_carts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(related_name='orders', to='clothing_store.item'),
        ),
    ]
