# Generated by Django 4.0.5 on 2022-06-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0006_alter_brand_name_alter_clothing_name'),
        ('orders', '0006_remove_order_carts_order_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(blank=True, to='clothing_store.item'),
        ),
    ]
