# Generated by Django 4.0.5 on 2022-06-13 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0004_remove_clothing_image'),
        ('basket', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='clothing_name',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothing_store.clothing'),
        ),
    ]
