# Generated by Django 4.0.5 on 2022-06-13 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0005_remove_cart_clothing_name_cart_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='product_quantity',
        ),
    ]
