# Generated by Django 4.0.5 on 2022-06-13 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothing_store', '0004_remove_clothing_image'),
        ('basket', '0007_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='clothing_store.clothing')),
            ],
            options={
                'verbose_name_plural': 'Корзина',
            },
        ),
    ]
