# Generated by Django 4.0.5 on 2022-06-13 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0009_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
