# Generated by Django 4.0.5 on 2022-06-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='clothes',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='product_quantity',
            new_name='clothes_quantity',
        ),
    ]
