# Generated by Django 4.0.5 on 2022-06-15 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing_store', '0004_remove_clothing_image'),
        ('basket', '0013_cart_created_at_cart_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='clothes_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='clothes',
        ),
        migrations.AddField(
            model_name='cart',
            name='clothes',
            field=models.ManyToManyField(related_name='clothes', to='clothing_store.clothing'),
        ),
    ]
