# Generated by Django 4.0.5 on 2022-06-29 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='update_date',
        ),
    ]
