# Generated by Django 4.0.5 on 2022-06-26 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to-do'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'completed')], default='PENDING', max_length=25),
        ),
    ]
