# Generated by Django 4.0.5 on 2022-06-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_completed_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='timestamp',
            new_name='creation_date',
        ),
    ]
