# Generated by Django 4.0.5 on 2022-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_timestamp_task_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateTimeField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
