# Generated by Django 4.0.5 on 2022-06-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_task_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='update_date',
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('TO_DO', 'to-do'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'completed')], default='TO_DO', max_length=25),
        ),
    ]
